permalink: /:title/
exclude:
  - COPYRIGHT
  - Gemfile
  - Gemfile.lock
  - lib
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor
timezone: Europe/Stockholm
url: 'https://spelkosmos.se'
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
plugins:
  - jekyll-sitemap
